// Copyright 2011 ZHU HAIHUA <kimiazhu@gmail.com>. 
// All rights reserved.
// Use of this source code is governed by MIT 
// license that can be found in the LICENSE file.

// Description: gap
// Author: ZHU HAIHUA
// Since: 2016-09-12 23:33
package gap

import "text/template"

var tmpl *template.Template

func init() {
	tmpl, err := template.New("vfstemplate").Parse(`package {{.Package}}

// This file was automatically generated by gap (github.com/kimiazhu/gap)
// at {{ .ParseDate.Format "2006-01-02T15:04:05-0700" }}; compression = {{ .Compression }}, {{ printf "%0.1f%% saved" .PctSavings }}



	`)
}
